### ISSUE TITLE
ATA driver problem

### ISSUE THREAD

**Issue by daniyalw** [dhavalhirdhav/LearnOS#30]
Whenever I try to do `ATA_wait_DRQ()`, it just hangs. It's a forever loop.

**Comment by xing1357** [comment]
`ATA_wait_DRQ()` waits for the `drq bit = 0`. If you are not doing any communicating with the ports, that bit will always be on.

**Comment by daniyalw** [comment]
Yep. It worked when I added a disk to QEMU.
